### PR TITLE
Added conditional future support for Markdown

### LINKED ISSUE #24: Markdown would be very nice
https://github.com/alps-io/spec/blob/master/draft-00.txt#L593-L597

### PR DESCRIPTION
**Pull request by Xophmeister**
Markdown, per draft-ietf-appsawg-text-markdown-05, MAY be supported in
`doc` and `ext` format attributes.

Closes #24

### CODE REVIEW

**Comment by fosrias** [comment]
I guess my only question is what is the value of saying is MAY be supported in the future vs. saying that you MAY use md based on the spec? @mamund Were you intimating some future support or were you implying righting MAY use now given the spec? I would vote the latter and call it a day for now. Thoughts?

**Comment by mamund** [comment]
@Xophmeister @fosdev 

yeah, what we need to do is to modify the text so that there is now a SHOULD list "text", "HTML", "ASCIIDOC" and a MAY list "markdown per raft-ietf-appsawg-text-markdown-05" (or some other text).

no need to put "futures" into the spec, just add it to the MAY list and people can implement as they wish.

cool?

**Comment by Xophmeister** [comment]
I am possibly misunderstanding entirely (sorry), but what would be the purpose of a SHOULD list *and* a MAY list? To me, that would read something like: "You must use one of these; oh, but you can also use any of those, too, if you like." It seems redundant, especially when the attribute is optional anyway.

Is it just to make explicit that Markdown -- and any other loosely defined formats that might find their way on to the MAY list -- ought to conform to a linked spec/RFC/I-D?

I'm cool with this change, but I'm just curious about the rationale behind it...

**Comment by fosrias** [comment]
I could go for SHOULD on HTML, but a MAY on both asciidoc and markdown per @Xophmeister's reasoning. Effectively, the latter two are most useful when they render to HTML anyhow, no?

**Comment by mamund** [comment]
MUST text, SHOULD html, MAY ASCIIDOC, markdown

Sound good?

**Comment by fosrias** [comment]
Doesn't MUST preclude the others? Think if you want it that way, SHOULD text and HTML and MAY asciidoc and markdown make more sense to me.

**Comment by mamund** [comment]
@fosrias : "preclude"?​

**Comment by fosrias** [comment]
Well, if I say you MUST use ‘text’, what room does that leave for anything else to be "compliant"? That is, if I MUST use text, then I preclude other choices in principle. Do we want to be that strict. There is no MUST on anything ATM other than that if a format is not specified, \<doc/> MUST be interpreted as text. It is a SHOULD on being `text`, ATM. Maybe I am missing something.

**Comment by fosrias** [comment]
@mamund So, short answer, is that what you had here is minimally correct and works for me:

>yeah, what we need to do is to modify the text so that there is now a SHOULD list "text", "HTML", "ASCIIDOC" and a MAY list "markdown per raft-ietf-appsawg-text-markdown-05" (or some other text).

Apparently my efforts to clarify for @Xophmeister confused things.

**Comment by mamund** [comment]
"MUST support text, SHOULD also support HTML and MAY support Asciidoc and
Markdown"​

**Comment by fosrias** [comment]
That makes all the difference :wink:, @mamund. That works for me.

**Comment by mamund** [comment]
@Xophmeister my sample text work for you, too?

**Comment by Xophmeister** [comment]
Yep, sounds good: I'll close this PR and make a new one...

**Pull request closed without merging**
